// Sélection ~75 aliments courants — extraits de la table CIQUAL 2025
const ALIMENTS_LIGHT = [
  {nom:"Abricot, dénoyauté, cru",pct:9},
  {nom:"Ananas, chair sans peau, cru",pct:11.7},
  {nom:"Banane, chair sans peau, crue",pct:19.7},
  {nom:"Beurre à 80% MG minimum, doux",pct:0.7},
  {nom:"Biscuit (génoise), fourré aux fruits (ex : orange, cerise…), nappé de chocolat",pct:66.6},
  {nom:"Biscotte au blé complet",pct:66},
  {nom:"Boulgour de blé, cru",pct:65.8},
  {nom:"Brioche, sans précision (aliment moyen)",pct:52.1},
  {nom:"Brocoli, bouilli/cuit à l'eau (aliment moyen)",pct:1},
  {nom:"Carotte, appertisée, égouttée",pct:3.3},
  {nom:"Cerise acérola, chair et peau, sans noyau, crue",pct:6.6},
  {nom:"Chocolat au lait, tablette",pct:58.9},
  {nom:"Chocolat noir 40% de cacao et plus, à pâtisser, tablette",pct:51.4},
  {nom:"Compote de pomme, allégée en sucres, rayon ambiant",pct:15.1},
  {nom:"Confiture, autres fruits ou mélange de fruits (extra ou classique)",pct:59.8},
  {nom:"Courgette, chair et peau, crue",pct:1.8},
  {nom:"Couscous au mouton",pct:12.2},
  {nom:"Crème dessert, allégée en matière grasse, rayon frais",pct:12.6},
  {nom:"Crêpe, nature, préemballée, rayon frais",pct:41.6},
  {nom:"Croissant, sans précision (aliment moyen)",pct:46.2},
  {nom:"Farine de blé tendre ou froment T110",pct:68.6},
  {nom:"Flocons d'avoine",pct:57.7},
  {nom:"Fraise, crue",pct:6},
  {nom:"Frites de pommes de terre, surgelées, cuites en friteuse",pct:32.7},
  {nom:"Fromage blanc, nature ou aux fruits (aliment moyen)",pct:6.3},
  {nom:"Galette de céréale(s) soufflée(s), aux graines",pct:77.7},
  {nom:"Gâteau (aliment moyen)",pct:51.8},
  {nom:"Glace au yaourt",pct:22.7},
  {nom:"Haricot blanc, appertisé, égoutté",pct:10.9},
  {nom:"Haricot rouge, appertisé, égoutté",pct:13},
  {nom:"Haricot vert, appertisé, égoutté",pct:2.1},
  {nom:"Jus d'orange, frais",pct:9.2},
  {nom:"Ketchup, préemballé",pct:23.7},
  {nom:"Kiwi, chair sans peau, avec pépins, cru",pct:11},
  {nom:"Lait demi-écrémé, UHT",pct:5},
  {nom:"Lentille, bouillie/cuite à l'eau (aliment moyen)",pct:16.2},
  {nom:"Limonade, sans précision sur la teneur en sucres et édulcorants (aliment moyen)",pct:7.1},
  {nom:"Maïs doux, appertisé, égoutté",pct:18.3},
  {nom:"Mangue, chair sans peau, sans noyau, crue",pct:14.3},
  {nom:"Mayonnaise (70% MG min.), préemballée",pct:3.4},
  {nom:"Melon cantaloup (par ex.: Charentais), chair sans peau, sans pépins, cru",pct:14.8},
  {nom:"Miel",pct:82.1},
  {nom:"Muesli (aliment moyen)",pct:63.4},
  {nom:"Orange, chair sans peau, sans pépins, crue",pct:8},
  {nom:"Pain au chocolat, artisanal",pct:45.4},
  {nom:"Pain blanc (par ex. : baguette, boule…)",pct:58.3},
  {nom:"Pain complet au seigle, préemballé",pct:39.5},
  {nom:"Pain de mie aux céréales et/ou graines, préemballé",pct:43.5},
  {nom:"Pastèque, chair sans peau, sans pépins, crue",pct:8.3},
  {nom:"Patate douce, crue",pct:17.1},
  {nom:"Petits pois, appertisés, égouttés",pct:13.7},
  {nom:"Pêche, chair et peau, sans noyau, crue",pct:7.5},
  {nom:"Pizza (aliment moyen)",pct:27.4},
  {nom:"Poire, chair et peau, crue",pct:12.3},
  {nom:"Pois chiche, appertisé, égoutté",pct:15},
  {nom:"Poivron, vert, jaune ou rouge, cru",pct:3.5},
  {nom:"Pomme de terre, appertisée, égouttée",pct:10.7},
  {nom:"Pomme, chair et peau, crue",pct:11.6},
  {nom:"Quinoa, bouilli/cuit à l'eau, sans sel ajouté",pct:27.9},
  {nom:"Raisin Chasselas, cru",pct:16.9},
  {nom:"Riz blanc, cru",pct:77.5},
  {nom:"Riz complet, cru",pct:71.4},
  {nom:"Semoule au lait, rayon frais",pct:18.9},
  {nom:"Sorbet, bâtonnet",pct:24.8},
  {nom:"Sucre blanc",pct:99.7},
  {nom:"Sushi ou maki aux produits de la mer",pct:26.9},
  {nom:"Tomate, chair et peau, bouillie/cuite à l'eau",pct:2.8},
  {nom:"Wrap jambon crudités",pct:25.2}
];
